# Generated by Django 4.2.9 on 2024-01-26 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SbitarApp', '0003_doctor_dob_doctor_email_doctor_experience_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='dob',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='email',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='experience',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='gender',
        ),
    ]
