# Generated by Django 4.2.9 on 2024-01-26 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SbitarApp', '0004_remove_doctor_dob_remove_doctor_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='dob',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='email',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='experience',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='gender',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
