# Generated by Django 4.2.9 on 2024-01-26 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SbitarApp', '0005_doctor_dob_doctor_email_doctor_experience_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, null=True)),
                ('last_name', models.CharField(max_length=255, null=True)),
                ('address', models.CharField(max_length=255, null=True)),
                ('email', models.CharField(max_length=50, null=True)),
                ('gender', models.CharField(max_length=15, null=True)),
                ('phone_number', models.CharField(max_length=15, null=True)),
                ('dob', models.DateField(null=True)),
            ],
        ),
    ]
