# Generated by Django 4.2.9 on 2024-01-26 22:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SbitarApp', '0006_patient'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(max_length=20)),
                ('appointment_date', models.DateField()),
                ('time_slot', models.CharField(max_length=10)),
                ('hospitalization', models.CharField(max_length=3)),
                ('problem', models.TextField()),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SbitarApp.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SbitarApp.patient')),
            ],
        ),
    ]
