# Generated by Django 4.2.9 on 2024-01-27 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SbitarApp', '0008_alter_appointment_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='status',
            field=models.CharField(default='pending', max_length=15),
        ),
    ]
