# Generated by Django 4.2.9 on 2024-01-27 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SbitarApp', '0010_roomallotment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='specialty',
            new_name='departement',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='experience',
        ),
        migrations.AddField(
            model_name='doctor',
            name='title',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
